#!/bin/bash
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local sessionid
    local -A vnc

    content="$(cat)"
    # tee >(base64 -d > /tmp/${sessionid}.$(date "+%Y-%m-%d-%H%M%S").png)

    sessionid="$1"
    if sessiondir=$(vnc_find_sessiondir "${sessionid}"); then
        sessionid=$(basename "$sessiondir")

        files_load_config --optional cluster-appliances config/cluster-appliances
        if [ "${cw_APPLIANCES_access_ADDRESS}" ]; then
            cat <<JSON | webapi_post --location "${cw_APPLIANCES_access_ADDRESS}/api/v1/sessions/${sessionid}/screenshot"
{
    "data": {
        "type": "screens",
        "attributes": {
            "content": "${content}"
        },
        "relationships": {
            "session": {
                 "data": {"type": "sessions", "id": "${sessionid}"}
            }
        }
    }
}
JSON
        fi
    fi
}

setup
require vnc
require webapi
require handler
require files

handler_tee main "$@"
