#!/bin/bash
################################################################################
##
## Alces Clusterware - Handler hook
## Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
##
################################################################################
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local storage_daemon_port access_daemon_port
    files_load_config instance config/cluster
    if [[ "${cw_INSTANCE_tag_STORAGE_ROLES}" == *":master:"* ]]; then	
	handler_iptables_insert INPUT -p tcp --dport "${cw_INSTANCE_tag_STORAGE_DAEMON_PORT:-25268}" -j ACCEPT
        if distro_start_service clusterware-alces-storage-manager-daemon; then
            echo "Alces Storage Manager Daemon service started"
        else
            echo "Unable to start Alces Storage Manager Daemon service"
        fi
    fi
    if [[ "${cw_INSTANCE_tag_ACCESS_ROLES}" == *":master:"* ]]; then	
	handler_iptables_insert INPUT -p tcp --dport "${cw_INSTANCE_tag_ACCESS_DAEMON_PORT:-25269}" -j ACCEPT
        if distro_start_service clusterware-alces-access-manager-daemon; then
            echo "Alces Access Manager Daemon service started"
        else
            echo "Unable to start Alces Access Manager Daemon service"
        fi
    fi
}

setup
require distro
require handler
require files

handler_tee main "$@"
